# Generated by Django 4.0 on 2022-07-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Informacionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('clienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacionapp.cliente')),
                ('sucursalFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacionapp.sucursal')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('inventarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventarioapp.inventario')),
                ('productoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacionapp.producto')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
