# Generated by Django 4.0 on 2022-07-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Informacionapp', '0001_initial'),
        ('Inventarioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registros',
            new_name='Registro',
        ),
    ]
