# Generated by Django 4.0 on 2022-07-08 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Informacionapp', '0001_initial'),
        ('Inventarioapp', '0002_rename_registros_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='clienteFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacionapp.cliente', verbose_name='Cliente'),
        ),
    ]
