# Generated by Django 4.0 on 2022-07-08 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Informacionapp', '0001_initial'),
        ('Inventarioapp', '0003_alter_inventario_clientefk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='clienteFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacionapp.cliente'),
        ),
    ]
