# Generated by Django 4.0 on 2022-07-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarioapp', '0006_alter_inventario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
